services:

  db:
    image: postgres:17-bookworm
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbcinema
      POSTGRES_USER: cinema
    ports:
      - 5032:5432
    volumes:
      - ./sql-init:/docker-entrypoint-initdb.d

  gui:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.org
      PGADMIN_DEFAULT_PASSWORD: password
